name: SFDX-CLI Deploy from Repository
on:                 
      push:
            branches: [ "main" ]
      pull_request:
            branches: [ "main" ]
jobs:
      SFDX-CLI-Deploy:
             runs-on: ubuntu-latest 
             steps:
                  - run: echo " GitHub Action running on ${{ runner.os }}"
                  - run:  echo "Retrieving ${{ github.ref }} from ${{ github.repository }}."
                  - uses: actions/checkout@v2
                  - run: npm install sfdx-cli -g
                  - run: |
                     echo y | sfdx plugins:install sfdx-git-delta
                          sfdx sgd:source:delta --to "HEAD" --from "HEAD^"  --ignore ignorefile --output "."
                          cat -d ./toDeploy
                  - run: sfdx force:source:convert -r ./force-app -d ./toDeploy
                  - run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key    
                  - run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --setdefaultdevhubusername
                  - run: sfdx force:mdapi:deploy -l RunLocalTests -d ./toDeploy -u kishansingh@deloitte.com
 
                  
